force-app/main/default/objects/Leaderboard__c/Leaderboard__c.object-meta.xml
<CustomObject>
    <label>Leaderboard</label>
    <nameField>
        <label>Leaderboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leaderboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leaderboard__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Badges</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/BadgesT__c.field-meta.xml
<CustomField>
    <fullName>BadgesT__c</fullName>
    <label>BadgesT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/First_Ascent__c.field-meta.xml
<CustomField>
    <fullName>First_Ascent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>First Ascent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/First_AscentT__c.field-meta.xml
<CustomField>
    <fullName>First_AscentT__c</fullName>
    <label>First AscentT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/NameT__c.field-meta.xml
<CustomField>
    <fullName>NameT__c</fullName>
    <label>NameT</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/SuperBadges__c.field-meta.xml
<CustomField>
    <fullName>SuperBadges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SuperBadges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/SuperBadgesT__c.field-meta.xml
<CustomField>
    <fullName>SuperBadgesT__c</fullName>
    <label>SuperBadgesT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/TotalPoints__c.field-meta.xml
<CustomField>
    <fullName>TotalPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TotalPoints</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/TotalPointsT__c.field-meta.xml
<CustomField>
    <fullName>TotalPointsT__c</fullName>
    <label>TotalPointsT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test3_readhtml2.cls
@isTest (SeeAllData=false)
private class Test3_readhtml2{
  static testMethod void Test_readhtml2(){ 
  String userid;
  string strpoints = '1000';
  string strhtml = 'data-test-user-name </h1> Michael Rucker' + 'data-test-points-count>253,354</div>';
      
        SingleRequestMock fakeResponse2 = new SingleRequestMock(301,'Complete',strhtml, null);
        Test.setMock(HttpCalloutMock.class, fakeResponse2);     
  readhtml2.getbody('005500000060PqcAAE'); 
  //005500000060PqcAAE
  //005F0000004ss8EIAQ
    
       if (strpoints > '' ) {   
             LeaderBoard__c newLB = new LeaderBoard__c();
             newLB.NameT__c = 'Michael Rucker';
             newLB.ID = 'a00410000012m66AAA';
             newLB.BadgesT__c = 1;
             newLB.First_AscentT__c = 1;
             newLB.TotalPointsT__c = 1;
             newLB.SuperBadgesT__c = 1; 
             
             //live fields
             newLB.Badges__c = 1; //intCB;  // - intCommunityB - intCBIP;
             newLB.First_Ascent__c = 1;
             newLB.TotalPoints__c = 1;
             newLB.SuperBadges__c = 1; 
             newLB.Name = 'Michael Rucker';

             update newLB;
             }
              
  }
  }