force-app/main/default/objects/Leaderboard__c/Leaderboard__c.object-meta.xml
<CustomObject>
    <label>Leaderboard</label>
    <nameField>
        <label>Leaderboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leaderboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leaderboard__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/UrlStatus__c.field-meta.xml
<CustomField>
    <fullName>UrlStatus__c</fullName>
    <label>UrlStatus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaderBoardTotalProfiles.cls
public class LeaderBoardTotalProfiles {
   public List<AggregateResult> getLeaderboards() {
    string results;
    List<String> someValues = new List<String>{'NOT FOUND', 'ERROR', 'MISSING'};
    List<AggregateResult> leaderboardsTotalProfiles = Database.query('SELECT count(id) tp FROM Leaderboard__c WHERE UrlStatus__c != :someValues and profile__c > \'\' ');
    system.debug('Total Profiles: ' + leaderboardsTotalProfiles);
    return leaderboardsTotalProfiles;
   }   
}