force-app/main/default/objects/Leaderboard__c/Leaderboard__c.object-meta.xml
<CustomObject>
    <label>Leaderboard</label>
    <nameField>
        <label>Leaderboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leaderboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leaderboard__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Badges</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Leaderboard__c/fields/UrlStatus__c.field-meta.xml
<CustomField>
    <fullName>UrlStatus__c</fullName>
    <label>UrlStatus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaderBoardTotalBadges.cls
public class LeaderBoardTotalBadges {
   public List<AggregateResult> getLeaderboards() {
    string results;
    List<String> someValues = new List<String>{'NOT FOUND', 'ERROR', 'MISSING'};
    List<AggregateResult> leaderboardsTtotalBadges = Database.query('SELECT sum(Badges__c) tp FROM Leaderboard__c WHERE UrlStatus__c != :someValues and profile__c > \'\'  ');
    system.debug('Results: ' + leaderboardsTtotalBadges);
    return leaderboardsTtotalBadges;
   }   
}