force-app/main/default/objects/TrailheadData__c/TrailheadData__c.object-meta.xml
<CustomObject>
    <label>TrailheadData</label>
    <nameField>
        <label>TrailheadData Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrailheadDatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrailheadData__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <externalId>true</externalId>
    <label>Name</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrailheadData__c/fields/THData__c.field-meta.xml
<CustomField>
    <fullName>THData__c</fullName>
    <label>THData</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TrailheadDataController.cls
public class TrailheadDataController {
   public List< AggregateResult > getLeaderboards() {
   string strname = 'Master';
    List< AggregateResult > leaderboards = Database.query(
         'SELECT thdata__c ' +
        'FROM trailheaddata__c ' +
        ' WHERE name__c = :strname  ' +
        ' group by thdata__c limit 1'
    );
    system.debug('Results: ' + leaderboards);
    return leaderboards;
   }   
}